[package]
name = "d06"
version = "0.1.0"
authors = ["ginglis13 <ginglis05@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
